export const CAR_BRANDS: Record<string, string[]> = {
  Alfa: ['147', '156', '159', 'Giulia', 'Giulietta', 'Stelvio', 'Brera', 'GT', 'Mito'],
  Audi: ['A3', 'A4', 'A4 Avant', 'A5', 'A6', 'A6 Avant', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'RS3', 'RS4', 'RS6', 'S3', 'S4', 'S5', 'TT'],
  BMW: ['1 Series', '2 Series', '3 Series', '5 Series', '525d', '530d', '7 Series', 'X1', 'X3', 'X5', 'X6', 'M3', 'M5', 'M2', 'Z4'],
  Chevrolet: ['Aveo', 'Cruze', 'Spark', 'Captiva', 'Epica', 'Lacetti'],
  Citroen: ['C1', 'C2', 'C3', 'C4', 'C5', 'Berlingo', 'DS3', 'DS4', 'DS5', 'Grand C4 Picasso', 'C-Elysee'],
  Dacia: ['Sandero', 'Logan', 'Duster', 'Dokker', 'Lodgy', 'Spring'],
  Fiat: ['500', '500L', '500X', 'Panda', 'Punto', 'Bravo', 'Stilo', 'Doblo', 'Tipo', 'Croma', 'Grande Punto'],
  Ford: ['Fiesta', 'Focus', 'Fusion', 'Mondeo', 'Kuga', 'Edge', 'Mustang', 'C-Max', 'S-Max', 'Galaxy', 'Ka', 'B-Max', 'EcoSport', 'Puma'],
  Honda: ['Civic', 'Accord', 'CR-V', 'HR-V', 'Jazz', 'City', 'Legend', 'Insight', 'CR-Z'],
  Hyundai: ['i10', 'i20', 'i30', 'Elantra', 'Accent', 'Tucson', 'Santa Fe', 'Sonata', 'Coupé', 'Kona', 'Ioniq'],
  Kia: ['Picanto', 'Rio', 'Ceed', 'Cerato', 'Sportage', 'Sorento', 'Optima', 'Soul', 'Stinger', 'Niro', 'Stonic'],
  Lada: ['Niva', 'Granta', 'Vesta', 'Kalina', 'Priora', 'Largus'],
  Land: ['Defender', 'Discovery', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Freelander'],
  Mazda: ['2', '3', '6', 'CX-3', 'CX-5', 'CX-7', 'CX-9', 'MX-5', 'RX-8', 'Premacy'],
  Mercedes: ['A Class', 'B Class', 'C Class', 'C Class T-Modell', 'E Class', 'CLS', 'CLA', 'GLA', 'GLC', 'GLE', 'GLS', 'S Class', 'SLK', 'SL', 'AMG GT', 'ML'],
  Mini: ['Cooper', 'Cooper S', 'Cooper D', 'Countryman', 'Clubman', 'Paceman', 'One'],
  Nissan: ['Micra', 'Note', 'Qashqai', 'Juke', 'X-Trail', 'Pathfinder', 'Navara', '370Z', 'GT-R', 'Leaf', 'Almera', 'Tiida'],
  Opel: ['Corsa', 'Astra', 'Astra H', 'Astra J', 'Astra K', 'Vectra', 'Insignia', 'Mokka', 'Zafira', 'Meriva', 'Combo', 'Kadett', 'Calibra', 'Tigra', 'Antara'],
  Peugeot: ['106', '206', '207', '208', '306', '307', '308', '406', '407', '508', '2008', '3008', '5008', 'Partner', 'Bipper', 'Expert', 'RCZ'],
  Renault: ['Clio', 'Megane', 'Captur', 'Kadjar', 'Scenic', 'Grand Scenic', 'Laguna', 'Talisman', 'Kangoo', 'Trafic', 'Twingo', 'Fluence', 'Symbol', 'Dokker', 'Koleos'],
  Seat: ['Ibiza', 'Leon', 'Toledo', 'Altea', 'Arona', 'Ateca', 'Tarraco', 'Alhambra', 'Exeo', 'Mii', 'Cordoba'],
  Skoda: ['Fabia', 'Octavia', 'Octavia Combi', 'Superb', 'Rapid', 'Scala', 'Kamiq', 'Karoq', 'Kodiaq', 'Citigo', 'Roomster', 'Yeti'],
  Subaru: ['Impreza', 'WRX', 'Forester', 'Outback', 'XV', 'Legacy', 'BRZ', 'Levorg'],
  Suzuki: ['Swift', 'Vitara', 'SX4', 'Baleno', 'Ignis', 'Celerio', 'Jimny', 'Kizashi'],
  Toyota: ['Yaris', 'Corolla', 'Auris', 'Avensis', 'Camry', 'RAV4', 'C-HR', 'Highlander', 'Hilux', 'GT86', 'Prius', 'Aygo', 'Land Cruiser'],
  Volkswagen: ['Golf', 'Golf GTI', 'Golf R', 'Polo', 'Passat', 'Passat Variant', 'Arteon', 'Tiguan', 'Touareg', 'T-Roc', 'T-Cross', 'Touran', 'Sharan', 'Beetle', 'Jetta', 'Bora', 'Caddy', 'Up'],
  Volvo: ['S40', 'S60', 'S80', 'V40', 'V50', 'V60', 'V70', 'XC40', 'XC60', 'XC90', 'C30', 'XC70'],
};

export const BRAND_NAMES = Object.keys(CAR_BRANDS).sort();
