import { Car, MyGarageCar } from '@/types';

export function formatEuro(amount: number): string {
  return new Intl.NumberFormat('sr-RS', {
    style: 'currency',
    currency: 'EUR',
    maximumFractionDigits: 0,
  }).format(amount);
}

/**
 * Always formatted with an explicit locale: a bare toLocaleString() resolves
 * differently on the Node server than in a Serbian browser, which shows up as
 * a hydration mismatch on every mileage figure.
 */
export function formatKm(km: number): string {
  return `${new Intl.NumberFormat('sr-RS').format(km)} km`;
}

export const MY_CAR: MyGarageCar = {
  id: 'my-bmw-e60',
  brand: 'BMW',
  model: '525d',
  generation: 'E60',
  year: 2005,
  bodyType: 'Sedan',
  color: 'Sapphire Black',
  mileage: 198000,
  price: 6500,
  city: 'Kosovska Mitrovica',
  country: 'Serbia',
  image: 'https://images.pexels.com/photos/11501007/pexels-photo-11501007.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  images: [
    'https://images.pexels.com/photos/11501007/pexels-photo-11501007.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    'https://images.pexels.com/photos/16439513/pexels-photo-16439513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    'https://images.pexels.com/photos/13058789/pexels-photo-13058789.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    'https://images.pexels.com/photos/12681046/pexels-photo-12681046.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  ],
  specs: {
    engine: 'BMW M57D25',
    displacement: '2.5L',
    cylinders: 6,
    power: '197 KS (145 kW)',
    torque: '410 Nm',
    fuelType: 'Diesel',
    transmission: 'Manual',
    drivetrain: 'RWD',
    topSpeed: '240 km/h',
    acceleration: '7.5s (0-100)',
  },
  owner: {
    name: 'Nikola V.',
    phone: '+381 64 123 4567',
    city: 'Kosovska Mitrovica',
    rating: 4.9,
  },
  description:
    'Odlično održavan BMW 525d E60 sa rednim šestocilindričnim dizelom. Stage 1 remap podiže snagu na ~215 KS. DPF uklonjen radi dugoročne pouzdanosti. Ugrađena Zeder brava na volanu.',
  modifications: [
    'Stage 1 ECU remap (+18 KS / +60 Nm)',
    'DPF uklonjen + prava cev',
    'Zeder sigurnosna brava volana',
    'H&R spuštene opruge',
    'Bilstein B6 amortizeri',
    'M-Sport prednji spojler',
  ],
  equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'zeder', 'isofix', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'navigation', 'bluetooth', 'trip_computer'],
  securityFeatures: ['Zeder brava volana', 'Alarmni sistem', 'GPS lokator'],
  buildNotes: [
    'Lanac razvoda zamenjen na 170.000 km',
    'Sve tečnosti zamenjene na poslednjem servisu',
    'Nove Michelin Pilot Sport 4 gume (sve četiri)',
    'Ugrađen swirl flap delete kit',
    'EGR hladnjak očišćen',
    'Nov akumulator (AGM 90Ah)',
  ],
  estimatedValue: 7200,
};

export const DEFAULT_GARAGE_CARS: MyGarageCar[] = [
  MY_CAR,
  {
    id: 'my-audi-a6',
    brand: 'Audi',
    model: 'A6',
    generation: 'C6',
    year: 2008,
    bodyType: 'Sedan',
    color: 'Phantom Black',
    mileage: 220000,
    price: 4200,
    city: 'Kosovska Mitrovica',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/16439513/pexels-photo-16439513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/16439513/pexels-photo-16439513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/8020807/pexels-photo-8020807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/17888846/pexels-photo-17888846.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/24742667/pexels-photo-24742667.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Audi 2.0 TDI BPW',
      displacement: '2.0L',
      cylinders: 4,
      power: '140 KS (103 kW)',
      torque: '320 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '215 km/h',
      acceleration: '9.6s (0-100)',
    },
    owner: {
      name: 'Nikola V.',
      phone: '+381 64 123 4567',
      city: 'Kosovska Mitrovica',
      rating: 4.9,
    },
    description:
      'Audi A6 C6 2.0 TDI za svakodnevnu vožnju. Čist lim, S-Line enterijer, originalne 17" alu felne. Plafon skoro presvučen.',
    modifications: ['S-Line prednja maska', 'Black optic paket'],
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'leather_seats', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
    securityFeatures: ['Fabrički alarm', 'Brava volana'],
    buildNotes: ['DPF uklonjen', 'Kvačilo zamenjeno na 190.000 km'],
    estimatedValue: 4500,
  },
];

export const MARKETPLACE_CARS: Car[] = [
  {
    id: 'audi-a4-b7-avant',
    brand: 'Audi',
    model: 'A4 Avant',
    generation: 'B7',
    year: 2006,
    bodyType: 'Caravan',
    color: 'Ibis White',
    mileage: 212000,
    price: 5800,
    city: 'Belgrade',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/37472548/pexels-photo-37472548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/37472548/pexels-photo-37472548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/5998732/pexels-photo-5998732.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/14541951/pexels-photo-14541951.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/11213779/pexels-photo-11213779.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW BLS / PD 105',
      displacement: '1.9L',
      cylinders: 4,
      power: '105 KS (77 kW)',
      torque: '250 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '188 km/h',
      acceleration: '11.2s (0-100)',
    },
    owner: {
      name: 'Marko D.',
      phone: '+381 63 987 6543',
      city: 'Belgrade',
      rating: 4.7,
    },
    description:
      'Pouzdan Audi A4 Avant 1.9 TDI u odličnom stanju. Originalna Audi Navigation Plus. Quattro-style felne, kompletna servisna istorija.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'auto_climate', 'cruise_control', 'electric_windows', 'alloy_wheels', 'led_xenon', 'panorama', 'fog_lights', 'navigation', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'vw-golf-5-gti',
    brand: 'Volkswagen',
    model: 'Golf GTI',
    generation: 'Mk5',
    year: 2007,
    bodyType: 'Hatchback',
    color: 'Tornado Red',
    mileage: 178000,
    price: 7200,
    city: 'Novi Sad',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/20809165/pexels-photo-20809165.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/20809165/pexels-photo-20809165.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28447302/pexels-photo-28447302.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28447308/pexels-photo-28447308.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28447331/pexels-photo-28447331.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW BPY 2.0 TFSI',
      displacement: '2.0L',
      cylinders: 4,
      power: '200 KS (147 kW)',
      torque: '280 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '243 km/h',
      acceleration: '6.9s (0-100)',
    },
    owner: {
      name: 'Stefan J.',
      phone: '+381 65 234 5678',
      city: 'Novi Sad',
      rating: 4.5,
    },
    description:
      'Čist Mk5 Golf GTI bez rđe. Recaro Sport sedišta, sportski auspuh, APR Stage 1 softver. Redovna zamena ulja 5W-40 potpuno sintetičkim.',
    modifications: [
      'APR Stage 1 čip (+30 KS)',
      'Milltek non-resonated catback izduv',
      'Forge DVR blow-off ventil',
    ],
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'navigation', 'bluetooth', 'reverse_camera', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'alfa-romeo-159',
    brand: 'Alfa Romeo',
    model: '159',
    generation: '939',
    year: 2008,
    bodyType: 'Sedan',
    color: 'Grigio Alfissimo',
    mileage: 165000,
    price: 4900,
    city: 'Nis',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/15515159/pexels-photo-15515159.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/15515159/pexels-photo-15515159.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15515192/pexels-photo-15515192.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/17720058/pexels-photo-17720058.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Alfa 939 A5.000',
      displacement: '1.9L',
      cylinders: 4,
      power: '150 KS (110 kW)',
      torque: '305 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'RWD',
      topSpeed: '215 km/h',
      acceleration: '8.5s (0-100)',
    },
    owner: {
      name: 'Aleksandar M.',
      phone: '+381 60 345 6789',
      city: 'Nis',
      rating: 4.3,
    },
    description:
      'Italijanska lepotica sa dušom. Alfa 159 1.9 JTDm, nov kaiš razvoda, nove kočnice svuda. Sitne nepravilnosti u laku na vozačevim vratima. Vozi besprekorno.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'leather_seats', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
  },
  {
    id: 'bmw-320d-e90',
    brand: 'BMW',
    model: '320d',
    generation: 'E90',
    year: 2009,
    bodyType: 'Sedan',
    color: 'Montego Blue',
    mileage: 195000,
    price: 8900,
    city: 'Subotica',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/31983216/pexels-photo-31983216.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/31983216/pexels-photo-31983216.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28522339/pexels-photo-28522339.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28522338/pexels-photo-28522338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/18542812/pexels-photo-18542812.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'BMW N47D20',
      displacement: '2.0L',
      cylinders: 4,
      power: '163 KS (120 kW)',
      torque: '340 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'RWD',
      topSpeed: '230 km/h',
      acceleration: '7.8s (0-100)',
    },
    owner: {
      name: 'Petar K.',
      phone: '+381 61 456 7890',
      city: 'Subotica',
      rating: 4.8,
    },
    description:
      'Facelift E90 320d sa M-Sport paketom. Potpuno električna sedišta, ksenon svetla, iDrive navigacija. Servisiran kod ovlašćenog BMW servisa do 120.000 km.',
    modifications: ['M-Sport branici i bočni pragovi', 'BMW Performance nastavci auspuha'],
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'leather_seats', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'panorama', 'fog_lights', 'navigation', 'bluetooth', 'reverse_camera', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'mercedes-w204-c220',
    brand: 'Mercedes-Benz',
    model: 'C 220 CDI',
    generation: 'W204',
    year: 2007,
    bodyType: 'Sedan',
    color: 'Obsidian Black',
    mileage: 230000,
    price: 6200,
    city: 'Kragujevac',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/15264253/pexels-photo-15264253.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/15264253/pexels-photo-15264253.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15844730/pexels-photo-15844730.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/31040120/pexels-photo-31040120.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Mercedes OM646',
      displacement: '2.2L',
      cylinders: 4,
      power: '170 KS (125 kW)',
      torque: '400 Nm',
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      topSpeed: '230 km/h',
      acceleration: '8.5s (0-100)',
    },
    owner: {
      name: 'Dejan S.',
      phone: '+381 62 111 2233',
      city: 'Kragujevac',
      rating: 4.6,
    },
    description:
      'Mercedes C 220 CDI W204, automatski menjač. Servisiran redovno, nove prednje kočnice. KompletanAMG paket: branici, pragovi, 18" felne.',
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'leather_seats', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'navigation', 'bluetooth', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'vw-passat-b6-variant',
    brand: 'Volkswagen',
    model: 'Passat Variant',
    generation: 'B6',
    year: 2008,
    bodyType: 'Caravan',
    color: 'Reflex Silver',
    mileage: 245000,
    price: 5400,
    city: 'Novi Sad',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/11490451/pexels-photo-11490451.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/11490451/pexels-photo-11490451.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15223421/pexels-photo-15223421.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15256364/pexels-photo-15256364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW BKP 2.0 TDI',
      displacement: '2.0L',
      cylinders: 4,
      power: '140 KS (103 kW)',
      torque: '320 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '210 km/h',
      acceleration: '9.8s (0-100)',
    },
    owner: {
      name: 'Ivan L.',
      phone: '+381 63 555 6677',
      city: 'Novi Sad',
      rating: 4.4,
    },
    description:
      'Prostran Passat Variant B6, idealan za porodicu. DPF uklonjen, klima punjena prošle godine. Manja ogrebotina na zadnjem braniku.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'honda-civic-8-gt',
    brand: 'Honda',
    model: 'Civic GT',
    generation: 'VIII',
    year: 2009,
    bodyType: 'Hatchback',
    color: 'Carbon Bronze',
    mileage: 168000,
    price: 7800,
    city: 'Belgrade',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/12821565/pexels-photo-12821565.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/12821565/pexels-photo-12821565.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/13118999/pexels-photo-13118999.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Honda R18A2',
      displacement: '1.8L',
      cylinders: 4,
      power: '140 KS (103 kW)',
      torque: '174 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '205 km/h',
      acceleration: '8.9s (0-100)',
    },
    owner: {
      name: 'Milan R.',
      phone: '+381 64 777 8899',
      city: 'Belgrade',
      rating: 4.8,
    },
    description:
      'Honda Civic VIII GT, ultimativna pouzdanost. Lanac razvoda zamenjen na 155.000 km. Sportska sedišta, navigacija, panoramo krov.',
    modifications: ['Honda HFP sportski izduv', 'Eibach pro-kit spuštene opruge'],
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'panorama', 'fog_lights', 'navigation', 'bluetooth', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'ford-focus-mk2',
    brand: 'Ford',
    model: 'Focus',
    generation: 'Mk2',
    year: 2006,
    bodyType: 'Hatchback',
    color: 'Moondust Silver',
    mileage: 198000,
    price: 3200,
    city: 'Cacak',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/27138933/pexels-photo-27138933.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/27138933/pexels-photo-27138933.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/27138982/pexels-photo-27138982.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/27138903/pexels-photo-27138903.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Ford HWDA 1.6 TDCI',
      displacement: '1.6L',
      cylinders: 4,
      power: '109 KS (80 kW)',
      torque: '240 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '188 km/h',
      acceleration: '11.5s (0-100)',
    },
    owner: {
      name: 'Zoran T.',
      phone: '+381 65 222 3344',
      city: 'Cacak',
      rating: 4.2,
    },
    description:
      'Ford Focus Mk2 1.6 TDCI, ekonomičan gradski auto. Nove gume napred, kvačilo zamenjeno pre 20.000 km. Mala ogrebotina na praznim vratima.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'manual_climate', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
  },
  {
    id: 'mazda-3-bl',
    brand: 'Mazda',
    model: '3',
    generation: 'BL',
    year: 2010,
    bodyType: 'Sedan',
    color: 'Crystal Red',
    mileage: 142000,
    price: 8400,
    city: 'Nis',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/16028417/pexels-photo-16028417.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/16028417/pexels-photo-16028417.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/16021636/pexels-photo-16021636.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Mazda MZR 2.0',
      displacement: '2.0L',
      cylinders: 4,
      power: '150 KS (110 kW)',
      torque: '187 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '200 km/h',
      acceleration: '9.2s (0-100)',
    },
    owner: {
      name: 'Filip N.',
      phone: '+381 60 999 0011',
      city: 'Nis',
      rating: 4.7,
    },
    description:
      'Mazda 3 BL 2.0, jedan vlasnik od novog. Perfektan laku, kompletan servis u Mazda servisu. Bose zvučni sistem, halogena svetla.',
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'bluetooth', 'reverse_camera', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'audi-a3-8p-sportback',
    brand: 'Audi',
    model: 'A3 Sportback',
    generation: '8P',
    year: 2009,
    bodyType: 'Hatchback',
    color: 'Ibis White',
    mileage: 175000,
    price: 6700,
    city: 'Subotica',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/4101746/pexels-photo-4101746.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/4101746/pexels-photo-4101746.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/37916276/pexels-photo-37916276.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW CAXA 1.4 TSI',
      displacement: '1.4L',
      cylinders: 4,
      power: '125 KS (92 kW)',
      torque: '200 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '205 km/h',
      acceleration: '9.5s (0-100)',
    },
    owner: {
      name: 'Aleksa B.',
      phone: '+381 61 444 5566',
      city: 'Subotica',
      rating: 4.5,
    },
    description:
      'Audi A3 Sportback 1.4 TSI, turbo i lanac zamenjeni na 160.000 km. S-Line enterijer, dvozonska klima, 17" alu felne. Nema rđe nigde.',
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'leather_seats', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'bluetooth', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'skoda-octavia-2-tsi',
    brand: 'Skoda',
    model: 'Octavia',
    generation: 'Mk2',
    year: 2011,
    bodyType: 'Sedan',
    color: 'Race Blue',
    mileage: 156000,
    price: 7100,
    city: 'Kraljevo',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/38446754/pexels-photo-38446754.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/38446754/pexels-photo-38446754.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15668129/pexels-photo-15668129.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW CAWA 1.8 TSI',
      displacement: '1.8L',
      cylinders: 4,
      power: '160 KS (118 kW)',
      torque: '250 Nm',
      fuelType: 'Petrol',
      transmission: 'Semi-Auto',
      drivetrain: 'FWD',
      topSpeed: '220 km/h',
      acceleration: '7.8s (0-100)',
    },
    owner: {
      name: 'Nemanja D.',
      phone: '+381 62 333 7788',
      city: 'Kraljevo',
      rating: 4.6,
    },
    description:
      'Skoda Octavia Mk2 1.8 TSI sa DSG menjačem. Lanac i kvačilo DSG zamenjeni na 140.000 km. Praktičan i brz auto za svaki dan.',
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'navigation', 'bluetooth', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'renault-megane-3',
    brand: 'Renault',
    model: 'Megane',
    generation: 'III',
    year: 2010,
    bodyType: 'Hatchback',
    color: 'Glacier White',
    mileage: 188000,
    price: 4100,
    city: 'Pancevo',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/30135418/pexels-photo-30135418.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/30135418/pexels-photo-30135418.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/20286882/pexels-photo-20286882.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Renault K9K 1.5 dCi',
      displacement: '1.5L',
      cylinders: 4,
      power: '110 KS (81 kW)',
      torque: '240 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '190 km/h',
      acceleration: '11.0s (0-100)',
    },
    owner: {
      name: 'Darko P.',
      phone: '+381 65 888 9900',
      city: 'Pancevo',
      rating: 4.1,
    },
    description:
      'Renault Megane III 1.5 dCi, vrlo ekonomičan. Turbina zamenjena pre godinu dana. TomTom navigacija, automatska klima. Neki manji tragovi na prednjem braniku.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'auto_climate', 'cruise_control', 'electric_windows', 'alloy_wheels', 'fog_lights', 'navigation', 'bluetooth', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'opel-astra-j',
    brand: 'Opel',
    model: 'Astra',
    generation: 'J',
    year: 2012,
    bodyType: 'Sedan',
    color: 'Sovereign Silver',
    mileage: 134000,
    price: 5500,
    city: 'Smederevo',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/18833317/pexels-photo-18833317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/18833317/pexels-photo-18833317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/18833314/pexels-photo-18833314.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Opel A14NET 1.4 Turbo',
      displacement: '1.4L',
      cylinders: 4,
      power: '140 KS (103 kW)',
      torque: '200 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '200 km/h',
      acceleration: '9.9s (0-100)',
    },
    owner: {
      name: 'Milos V.',
      phone: '+381 64 666 2233',
      city: 'Smederevo',
      rating: 4.3,
    },
    description:
      'Opel Astra J 1.4 Turbo, niska kilometraža za godište. Jedan vlasnik, servisna knjiga. Ksenon svetla, grejanje sedišta, 16" felne.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'bluetooth', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'mercedes-clc-coupe',
    brand: 'Mercedes-Benz',
    model: 'CLC 200 Kompressor',
    generation: 'CL203',
    year: 2008,
    bodyType: 'Coupe',
    color: 'Iridium Silver',
    mileage: 175000,
    price: 9200,
    city: 'Belgrade',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/112452/pexels-photo-112452.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/112452/pexels-photo-112452.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/4692094/pexels-photo-4692094.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Mercedes M271 1.8 Kompressor',
      displacement: '1.8L',
      cylinders: 4,
      power: '184 KS (135 kW)',
      torque: '250 Nm',
      fuelType: 'Petrol',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      topSpeed: '235 km/h',
      acceleration: '8.2s (0-100)',
    },
    owner: {
      name: 'Bogdan M.',
      phone: '+381 61 555 1122',
      city: 'Belgrade',
      rating: 4.9,
    },
    description:
      'Mercedes CLC 200 Kompressor, kupe sa sportskim DNA. AMG paket: 18" felne, sportsko ogibljenje, crni enterijer. Naoštrena vožnja, bez ulaganja.',
    modifications: ['AMG 18" felne', 'Sportsko ogibljenje H&R', 'Brabus prednji splitter'],
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'leather_seats', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'panorama', 'fog_lights', 'navigation', 'bluetooth', 'trip_computer'],
  },
];
