import { Car, MyGarageCar } from '@/types';

export function formatEuro(amount: number): string {
  return new Intl.NumberFormat('sr-RS', {
    style: 'currency',
    currency: 'EUR',
    maximumFractionDigits: 0,
  }).format(amount);
}

/**
 * Always formatted with an explicit locale: a bare toLocaleString() resolves
 * differently on the Node server than in a Serbian browser, which shows up as
 * a hydration mismatch on every mileage figure.
 */
export function formatKm(km: number): string {
  return `${new Intl.NumberFormat('sr-RS').format(km)} km`;
}

export const MY_CAR: MyGarageCar = {
  id: 'my-bmw-e60',
  brand: 'BMW',
  model: '525d',
  generation: 'E60',
  year: 2005,
  bodyType: 'Sedan',
  color: 'Sapphire Black',
  mileage: 198000,
  price: 6500,
  city: 'Kosovska Mitrovica',
  country: 'Serbia',
  image: 'https://images.pexels.com/photos/11501007/pexels-photo-11501007.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  images: [
    'https://images.pexels.com/photos/11501007/pexels-photo-11501007.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    'https://images.pexels.com/photos/16439513/pexels-photo-16439513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    'https://images.pexels.com/photos/13058789/pexels-photo-13058789.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    'https://images.pexels.com/photos/12681046/pexels-photo-12681046.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  ],
  specs: {
    engine: 'BMW M57D25',
    displacement: '2.5L',
    cylinders: 6,
    power: '197 KS (145 kW)',
    torque: '410 Nm',
    fuelType: 'Diesel',
    transmission: 'Manual',
    drivetrain: 'RWD',
    topSpeed: '240 km/h',
    acceleration: '7.5s (0-100)',
  },
  owner: {
    name: 'Nikola V.',
    phone: '+381 64 123 4567',
    city: 'Kosovska Mitrovica',
    rating: 4.9,
  },
  description:
    'Odlično održavan BMW 525d E60 sa rednim šestocilindričnim dizelom. Stage 1 remap podiže snagu na ~215 KS. DPF uklonjen radi dugoročne pouzdanosti. Ugrađena Zeder brava na volanu.',
  modifications: [
    'Stage 1 ECU remap (+18 KS / +60 Nm)',
    'DPF uklonjen + prava cev',
    'Zeder sigurnosna brava volana',
    'H&R spuštene opruge',
    'Bilstein B6 amortizeri',
    'M-Sport prednji spojler',
  ],
  equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'zeder', 'isofix', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'navigation', 'bluetooth', 'trip_computer'],
  securityFeatures: ['Zeder brava volana', 'Alarmni sistem', 'GPS lokator'],
  buildNotes: [
    'Lanac razvoda zamenjen na 170.000 km',
    'Sve tečnosti zamenjene na poslednjem servisu',
    'Nove Michelin Pilot Sport 4 gume (sve četiri)',
    'Ugrađen swirl flap delete kit',
    'EGR hladnjak očišćen',
    'Nov akumulator (AGM 90Ah)',
  ],
  estimatedValue: 7200,
};

export const DEFAULT_GARAGE_CARS: MyGarageCar[] = [
  MY_CAR,
  {
    id: 'my-audi-a6',
    brand: 'Audi',
    model: 'A6',
    generation: 'C6',
    year: 2008,
    bodyType: 'Sedan',
    color: 'Phantom Black',
    mileage: 220000,
    price: 4200,
    city: 'Kosovska Mitrovica',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/16439513/pexels-photo-16439513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/16439513/pexels-photo-16439513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/8020807/pexels-photo-8020807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/17888846/pexels-photo-17888846.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/24742667/pexels-photo-24742667.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Audi 2.0 TDI BPW',
      displacement: '2.0L',
      cylinders: 4,
      power: '140 KS (103 kW)',
      torque: '320 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '215 km/h',
      acceleration: '9.6s (0-100)',
    },
    owner: {
      name: 'Nikola V.',
      phone: '+381 64 123 4567',
      city: 'Kosovska Mitrovica',
      rating: 4.9,
    },
    description:
      'Audi A6 C6 2.0 TDI za svakodnevnu vožnju. Čist lim, S-Line enterijer, originalne 17" alu felne. Plafon skoro presvučen.',
    modifications: ['S-Line prednja maska', 'Black optic paket'],
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'leather_seats', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
    securityFeatures: ['Fabrički alarm', 'Brava volana'],
    buildNotes: ['DPF uklonjen', 'Kvačilo zamenjeno na 190.000 km'],
    estimatedValue: 4500,
  },
];

export const MARKETPLACE_CARS: Car[] = [
  {
    id: 'audi-a4-b7-avant',
    brand: 'Audi',
    model: 'A4 Avant',
    generation: 'B7',
    year: 2006,
    bodyType: 'Caravan',
    color: 'Ibis White',
    mileage: 212000,
    price: 5800,
    city: 'Belgrade',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/37472548/pexels-photo-37472548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/37472548/pexels-photo-37472548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/5998732/pexels-photo-5998732.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/14541951/pexels-photo-14541951.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/11213779/pexels-photo-11213779.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW BLS / PD 105',
      displacement: '1.9L',
      cylinders: 4,
      power: '105 KS (77 kW)',
      torque: '250 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '188 km/h',
      acceleration: '11.2s (0-100)',
    },
    owner: {
      name: 'Marko D.',
      phone: '+381 63 987 6543',
      city: 'Belgrade',
      rating: 4.7,
    },
    description:
      'Pouzdan Audi A4 Avant 1.9 TDI u odličnom stanju. Originalna Audi Navigation Plus. Quattro-style felne, kompletna servisna istorija.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'auto_climate', 'cruise_control', 'electric_windows', 'alloy_wheels', 'led_xenon', 'panorama', 'fog_lights', 'navigation', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'vw-golf-5-gti',
    brand: 'Volkswagen',
    model: 'Golf GTI',
    generation: 'Mk5',
    year: 2007,
    bodyType: 'Hatchback',
    color: 'Tornado Red',
    mileage: 178000,
    price: 7200,
    city: 'Novi Sad',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/20809165/pexels-photo-20809165.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/20809165/pexels-photo-20809165.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28447302/pexels-photo-28447302.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28447308/pexels-photo-28447308.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28447331/pexels-photo-28447331.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW BPY 2.0 TFSI',
      displacement: '2.0L',
      cylinders: 4,
      power: '200 KS (147 kW)',
      torque: '280 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '243 km/h',
      acceleration: '6.9s (0-100)',
    },
    owner: {
      name: 'Stefan J.',
      phone: '+381 65 234 5678',
      city: 'Novi Sad',
      rating: 4.5,
    },
    description:
      'Čist Mk5 Golf GTI bez rđe. Recaro Sport sedišta, sportski auspuh, APR Stage 1 softver. Redovna zamena ulja 5W-40 potpuno sintetičkim.',
    modifications: [
      'APR Stage 1 čip (+30 KS)',
      'Milltek non-resonated catback izduv',
      'Forge DVR blow-off ventil',
    ],
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'navigation', 'bluetooth', 'reverse_camera', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'alfa-romeo-159',
    brand: 'Alfa Romeo',
    model: '159',
    generation: '939',
    year: 2008,
    bodyType: 'Sedan',
    color: 'Grigio Alfissimo',
    mileage: 165000,
    price: 4900,
    city: 'Nis',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/15515159/pexels-photo-15515159.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/15515159/pexels-photo-15515159.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15515192/pexels-photo-15515192.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/17720058/pexels-photo-17720058.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Alfa 939 A5.000',
      displacement: '1.9L',
      cylinders: 4,
      power: '150 KS (110 kW)',
      torque: '305 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'RWD',
      topSpeed: '215 km/h',
      acceleration: '8.5s (0-100)',
    },
    owner: {
      name: 'Aleksandar M.',
      phone: '+381 60 345 6789',
      city: 'Nis',
      rating: 4.3,
    },
    description:
      'Italijanska lepotica sa dušom. Alfa 159 1.9 JTDm, nov kaiš razvoda, nove kočnice svuda. Sitne nepravilnosti u laku na vozačevim vratima. Vozi besprekorno.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'leather_seats', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
  },
  {
    id: 'bmw-320d-e90',
    brand: 'BMW',
    model: '320d',
    generation: 'E90',
    year: 2009,
    bodyType: 'Sedan',
    color: 'Montego Blue',
    mileage: 195000,
    price: 8900,
    city: 'Subotica',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/31983216/pexels-photo-31983216.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/31983216/pexels-photo-31983216.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28522339/pexels-photo-28522339.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28522338/pexels-photo-28522338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/18542812/pexels-photo-18542812.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'BMW N47D20',
      displacement: '2.0L',
      cylinders: 4,
      power: '163 KS (120 kW)',
      torque: '340 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'RWD',
      topSpeed: '230 km/h',
      acceleration: '7.8s (0-100)',
    },
    owner: {
      name: 'Petar K.',
      phone: '+381 61 456 7890',
      city: 'Subotica',
      rating: 4.8,
    },
    description:
      'Facelift E90 320d sa M-Sport paketom. Potpuno električna sedišta, ksenon svetla, iDrive navigacija. Servisiran kod ovlašćenog BMW servisa do 120.000 km.',
    modifications: ['M-Sport branici i bočni pragovi', 'BMW Performance nastavci auspuha'],
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'leather_seats', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'panorama', 'fog_lights', 'navigation', 'bluetooth', 'reverse_camera', 'parking_sensors', 'trip_computer'],
  },
];
