import { Car, MyGarageCar } from '@/types';

export function formatEuro(amount: number): string {
  return new Intl.NumberFormat('sr-RS', {
    style: 'currency',
    currency: 'EUR',
    maximumFractionDigits: 0,
  }).format(amount);
}

/**
 * Always formatted with an explicit locale: a bare toLocaleString() resolves
 * differently on the Node server than in a Serbian browser, which shows up as
 * a hydration mismatch on every mileage figure.
 */
export function formatKm(km: number): string {
  return `${new Intl.NumberFormat('sr-RS').format(km)} km`;
}

export const MY_CAR: MyGarageCar = {
  id: 'my-bmw-e60',
  brand: 'BMW',
  model: '525d',
  generation: 'E60',
  year: 2005,
  bodyType: 'Sedan',
  color: 'Sapphire Black',
  mileage: 198000,
  price: 6500,
  city: 'Kosovska Mitrovica',
  country: 'Serbia',
  image: 'https://images.pexels.com/photos/11501007/pexels-photo-11501007.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  images: [
    'https://images.pexels.com/photos/11501007/pexels-photo-11501007.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    'https://images.pexels.com/photos/16439513/pexels-photo-16439513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    'https://images.pexels.com/photos/13058789/pexels-photo-13058789.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    'https://images.pexels.com/photos/12681046/pexels-photo-12681046.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  ],
  specs: {
    engine: 'BMW M57D25',
    displacement: '2.5L',
    cylinders: 6,
    power: '197 KS (145 kW)',
    torque: '410 Nm',
    fuelType: 'Diesel',
    transmission: 'Manual',
    drivetrain: 'RWD',
    topSpeed: '240 km/h',
    acceleration: '7.5s (0-100)',
  },
  owner: {
    name: 'Nikola V.',
    phone: '+381 64 123 4567',
    city: 'Kosovska Mitrovica',
    rating: 4.9,
  },
  description:
    'Odlično održavan BMW 525d E60 sa rednim šestocilindričnim dizelom. Stage 1 remap podiže snagu na ~215 KS. DPF uklonjen radi dugoročne pouzdanosti. Ugrađena Zeder brava na volanu.',
  modifications: [
    'Stage 1 ECU remap (+18 KS / +60 Nm)',
    'DPF uklonjen + prava cev',
    'Zeder sigurnosna brava volana',
    'H&R spuštene opruge',
    'Bilstein B6 amortizeri',
    'M-Sport prednji spojler',
  ],
  equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'zeder', 'isofix', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'navigation', 'bluetooth', 'trip_computer'],
  securityFeatures: ['Zeder brava volana', 'Alarmni sistem', 'GPS lokator'],
  buildNotes: [
    'Lanac razvoda zamenjen na 170.000 km',
    'Sve tečnosti zamenjene na poslednjem servisu',
    'Nove Michelin Pilot Sport 4 gume (sve četiri)',
    'Ugrađen swirl flap delete kit',
    'EGR hladnjak očišćen',
    'Nov akumulator (AGM 90Ah)',
  ],
  estimatedValue: 7200,
};

export const DEFAULT_GARAGE_CARS: MyGarageCar[] = [
  MY_CAR,
  {
    id: 'my-audi-a6',
    brand: 'Audi',
    model: 'A6',
    generation: 'C6',
    year: 2008,
    bodyType: 'Sedan',
    color: 'Phantom Black',
    mileage: 220000,
    price: 4200,
    city: 'Kosovska Mitrovica',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/16439513/pexels-photo-16439513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/16439513/pexels-photo-16439513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/8020807/pexels-photo-8020807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/17888846/pexels-photo-17888846.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/24742667/pexels-photo-24742667.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Audi 2.0 TDI BPW',
      displacement: '2.0L',
      cylinders: 4,
      power: '140 KS (103 kW)',
      torque: '320 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '215 km/h',
      acceleration: '9.6s (0-100)',
    },
    owner: {
      name: 'Nikola V.',
      phone: '+381 64 123 4567',
      city: 'Kosovska Mitrovica',
      rating: 4.9,
    },
    description:
      'Audi A6 C6 2.0 TDI za svakodnevnu vožnju. Čist lim, S-Line enterijer, originalne 17" alu felne. Plafon skoro presvučen.',
    modifications: ['S-Line prednja maska', 'Black optic paket'],
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'leather_seats', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
    securityFeatures: ['Fabrički alarm', 'Brava volana'],
    buildNotes: ['DPF uklonjen', 'Kvačilo zamenjeno na 190.000 km'],
    estimatedValue: 4500,
  },
];

export const MARKETPLACE_CARS: Car[] = [
  {
    id: 'audi-a4-b7-avant',
    brand: 'Audi',
    model: 'A4 Avant',
    generation: 'B7',
    year: 2006,
    bodyType: 'Caravan',
    color: 'Ibis White',
    mileage: 212000,
    price: 5800,
    city: 'Belgrade',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/37472548/pexels-photo-37472548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/37472548/pexels-photo-37472548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/5998732/pexels-photo-5998732.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/14541951/pexels-photo-14541951.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/11213779/pexels-photo-11213779.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW BLS / PD 105',
      displacement: '1.9L',
      cylinders: 4,
      power: '105 KS (77 kW)',
      torque: '250 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '188 km/h',
      acceleration: '11.2s (0-100)',
    },
    owner: {
      name: 'Marko D.',
      phone: '+381 63 987 6543',
      city: 'Belgrade',
      rating: 4.7,
    },
    description:
      'Pouzdan Audi A4 Avant 1.9 TDI u odličnom stanju. Originalna Audi Navigation Plus. Quattro-style felne, kompletna servisna istorija.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'auto_climate', 'cruise_control', 'electric_windows', 'alloy_wheels', 'led_xenon', 'panorama', 'fog_lights', 'navigation', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'vw-golf-5-gti',
    brand: 'Volkswagen',
    model: 'Golf GTI',
    generation: 'Mk5',
    year: 2007,
    bodyType: 'Hatchback',
    color: 'Tornado Red',
    mileage: 178000,
    price: 7200,
    city: 'Novi Sad',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/20809165/pexels-photo-20809165.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/20809165/pexels-photo-20809165.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28447302/pexels-photo-28447302.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28447308/pexels-photo-28447308.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28447331/pexels-photo-28447331.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW BPY 2.0 TFSI',
      displacement: '2.0L',
      cylinders: 4,
      power: '200 KS (147 kW)',
      torque: '280 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '243 km/h',
      acceleration: '6.9s (0-100)',
    },
    owner: {
      name: 'Stefan J.',
      phone: '+381 65 234 5678',
      city: 'Novi Sad',
      rating: 4.5,
    },
    description:
      'Čist Mk5 Golf GTI bez rđe. Recaro Sport sedišta, sportski auspuh, APR Stage 1 softver. Redovna zamena ulja 5W-40 potpuno sintetičkim.',
    modifications: [
      'APR Stage 1 čip (+30 KS)',
      'Milltek non-resonated catback izduv',
      'Forge DVR blow-off ventil',
    ],
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'navigation', 'bluetooth', 'reverse_camera', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'alfa-romeo-159',
    brand: 'Alfa Romeo',
    model: '159',
    generation: '939',
    year: 2008,
    bodyType: 'Sedan',
    color: 'Grigio Alfissimo',
    mileage: 165000,
    price: 4900,
    city: 'Nis',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/15515159/pexels-photo-15515159.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/15515159/pexels-photo-15515159.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15515192/pexels-photo-15515192.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/17720058/pexels-photo-17720058.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Alfa 939 A5.000',
      displacement: '1.9L',
      cylinders: 4,
      power: '150 KS (110 kW)',
      torque: '305 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'RWD',
      topSpeed: '215 km/h',
      acceleration: '8.5s (0-100)',
    },
    owner: {
      name: 'Aleksandar M.',
      phone: '+381 60 345 6789',
      city: 'Nis',
      rating: 4.3,
    },
    description:
      'Italijanska lepotica sa dušom. Alfa 159 1.9 JTDm, nov kaiš razvoda, nove kočnice svuda. Sitne nepravilnosti u laku na vozačevim vratima. Vozi besprekorno.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'leather_seats', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
  },
  {
    id: 'bmw-320d-e90',
    brand: 'BMW',
    model: '320d',
    generation: 'E90',
    year: 2009,
    bodyType: 'Sedan',
    color: 'Montego Blue',
    mileage: 195000,
    price: 8900,
    city: 'Subotica',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/31983216/pexels-photo-31983216.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/31983216/pexels-photo-31983216.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28522339/pexels-photo-28522339.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28522338/pexels-photo-28522338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/18542812/pexels-photo-18542812.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'BMW N47D20',
      displacement: '2.0L',
      cylinders: 4,
      power: '163 KS (120 kW)',
      torque: '340 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'RWD',
      topSpeed: '230 km/h',
      acceleration: '7.8s (0-100)',
    },
    owner: {
      name: 'Petar K.',
      phone: '+381 61 456 7890',
      city: 'Subotica',
      rating: 4.8,
    },
    description:
      'Facelift E90 320d sa M-Sport paketom. Potpuno električna sedišta, ksenon svetla, iDrive navigacija. Servisiran kod ovlašćenog BMW servisa do 120.000 km.',
    modifications: ['M-Sport branici i bočni pragovi', 'BMW Performance nastavci auspuha'],
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'leather_seats', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'panorama', 'fog_lights', 'navigation', 'bluetooth', 'reverse_camera', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'mercedes-c220-w204',
    brand: 'Mercedes-Benz',
    model: 'C 220 CDI',
    generation: 'W204',
    year: 2009,
    bodyType: 'Sedan',
    color: 'Obsidian Black',
    mileage: 201000,
    price: 7400,
    city: 'Belgrade',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/16284837/pexels-photo-16284837.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/16284837/pexels-photo-16284837.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/27019870/pexels-photo-27019870.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/16439646/pexels-photo-16439646.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Mercedes OM651',
      displacement: '2.2L',
      cylinders: 4,
      power: '170 KS (125 kW)',
      torque: '400 Nm',
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      topSpeed: '230 km/h',
      acceleration: '8.0s (0-100)',
    },
    owner: {
      name: 'Dejan S.',
      phone: '+381 62 111 2233',
      city: 'Belgrade',
      rating: 4.6,
    },
    description:
      'Mercedes C 220 CDI W204 facelift, automatski menjač. AMG paket, kožna sedišta, panoram. Redovno servisiran, bez skrivenih mana.',
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'leather_seats', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'panorama', 'fog_lights', 'navigation', 'bluetooth', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'vw-passat-b6-variant',
    brand: 'Volkswagen',
    model: 'Passat Variant',
    generation: 'B6',
    year: 2008,
    bodyType: 'Caravan',
    color: 'Reflex Silver',
    mileage: 230000,
    price: 4500,
    city: 'Novi Sad',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/15256362/pexels-photo-15256362.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/15256362/pexels-photo-15256362.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15223421/pexels-photo-15223421.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15256364/pexels-photo-15256364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW BMR 2.0 TDI',
      displacement: '2.0L',
      cylinders: 4,
      power: '140 KS (103 kW)',
      torque: '320 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '210 km/h',
      acceleration: '9.8s (0-100)',
    },
    owner: {
      name: 'Milan R.',
      phone: '+381 63 222 3344',
      city: 'Novi Sad',
      rating: 4.4,
    },
    description:
      'Passat B6 Variant 2.0 TDI, ogroman gepek. Idealna porodična kola. DPF uklonjen, nove prednje kočnice. Male tragove parkinga na braniku.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'bmw-320d-touring-e91',
    brand: 'BMW',
    model: '320d Touring',
    generation: 'E91',
    year: 2007,
    bodyType: 'Caravan',
    color: 'Alpine White',
    mileage: 188000,
    price: 6800,
    city: 'Nis',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/32724480/pexels-photo-32724480.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/32724480/pexels-photo-32724480.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/32724493/pexels-photo-32724493.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'BMW N47D20',
      displacement: '2.0L',
      cylinders: 4,
      power: '163 KS (120 kW)',
      torque: '340 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'RWD',
      topSpeed: '225 km/h',
      acceleration: '8.1s (0-100)',
    },
    owner: {
      name: 'Nemanja T.',
      phone: '+381 60 333 4455',
      city: 'Nis',
      rating: 4.7,
    },
    description:
      'BMW 320d Touring E91, M-Sport paket, koža, ksenon. Prvi vlasnik, servisna knjiga. Zadnji amortizeri zamenjeni prošle godine.',
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'leather_seats', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'fog_lights', 'navigation', 'bluetooth', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'audi-a3-8p',
    brand: 'Audi',
    model: 'A3 Sportback',
    generation: '8P',
    year: 2006,
    bodyType: 'Hatchback',
    color: 'Sprint Red',
    mileage: 175000,
    price: 4200,
    city: 'Kragujevac',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/37916276/pexels-photo-37916276.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/37916276/pexels-photo-37916276.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/37916207/pexels-photo-37916207.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/37916267/pexels-photo-37916267.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Audi BKC 1.9 TDI',
      displacement: '1.9L',
      cylinders: 4,
      power: '105 KS (77 kW)',
      torque: '250 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '187 km/h',
      acceleration: '11.3s (0-100)',
    },
    owner: {
      name: 'Filip N.',
      phone: '+381 64 444 5566',
      city: 'Kragujevac',
      rating: 4.2,
    },
    description:
      'Audi A3 Sportback 1.9 TDI, štedljiv i pouzdan. S-Line enterijer, 17" felne. Tajming menjan na 160.000 km. Mala ogrebotina na zadnjem braniku.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
  },
  {
    id: 'honda-civic-8g',
    brand: 'Honda',
    model: 'Civic',
    generation: '8G',
    year: 2008,
    bodyType: 'Hatchback',
    color: 'Nighthawk Black',
    mileage: 165000,
    price: 5500,
    city: 'Subotica',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/13118999/pexels-photo-13118999.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/13118999/pexels-photo-13118999.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/17364010/pexels-photo-17364010.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Honda R18A2',
      displacement: '1.8L',
      cylinders: 4,
      power: '140 KS (103 kW)',
      torque: '174 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '210 km/h',
      acceleration: '9.1s (0-100)',
    },
    owner: {
      name: 'Goran L.',
      phone: '+381 65 555 6677',
      city: 'Subotica',
      rating: 4.8,
    },
    description:
      'Honda Civic 1.8 i-VTEC, besprekorno održavana. Originalna boja, bez rđe. Koža, navigacija, sve funkcionalno. Vlasnik iz Japana.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'leather_seats', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'navigation', 'bluetooth', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'toyota-corolla-e150',
    brand: 'Toyota',
    model: 'Corolla',
    generation: 'E150',
    year: 2009,
    bodyType: 'Sedan',
    color: 'White Pearl',
    mileage: 155000,
    price: 6200,
    city: 'Belgrade',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/37620310/pexels-photo-37620310.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/37620310/pexels-photo-37620310.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Toyota 1ZR-FAE',
      displacement: '1.6L',
      cylinders: 4,
      power: '132 KS (97 kW)',
      torque: '160 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '195 km/h',
      acceleration: '10.4s (0-100)',
    },
    owner: {
      name: 'Slobodan V.',
      phone: '+381 61 666 7788',
      city: 'Belgrade',
      rating: 4.9,
    },
    description:
      'Toyota Corolla 1.6 Valvematic, najpouzdanija u klasi. Prvi vlasnik, servisna knjiga kod ovlašćenog servisa. Klima, tempomat, sve radi.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
  },
  {
    id: 'mazda-3-bl',
    brand: 'Mazda',
    model: '3',
    generation: 'BL',
    year: 2010,
    bodyType: 'Sedan',
    color: 'Velocity Red',
    mileage: 142000,
    price: 5900,
    city: 'Novi Sad',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/16028417/pexels-photo-16028417.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/16028417/pexels-photo-16028417.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/16021639/pexels-photo-16021639.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Mazda MZR 1.6',
      displacement: '1.6L',
      cylinders: 4,
      power: '105 KS (77 kW)',
      torque: '145 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '185 km/h',
      acceleration: '10.7s (0-100)',
    },
    owner: {
      name: 'Marija P.',
      phone: '+381 62 777 8899',
      city: 'Novi Sad',
      rating: 4.5,
    },
    description:
      'Mazda 3 BL 1.6, atraktivan dizajn. Boja u odličnom stanju, koža, klima. Mala potrošnja, idealna za grad i put. Redovan servis.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'leather_seats', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
  },
  {
    id: 'ford-focus-mk2',
    brand: 'Ford',
    model: 'Focus',
    generation: 'Mk2',
    year: 2007,
    bodyType: 'Hatchback',
    color: 'Moondust Silver',
    mileage: 198000,
    price: 3200,
    city: 'Nis',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/27138933/pexels-photo-27138933.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/27138933/pexels-photo-27138933.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/27138903/pexels-photo-27138903.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/27138926/pexels-photo-27138926.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Ford HHDA 1.8',
      displacement: '1.8L',
      cylinders: 4,
      power: '125 KS (92 kW)',
      torque: '165 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '195 km/h',
      acceleration: '10.0s (0-100)',
    },
    owner: {
      name: 'Zoran K.',
      phone: '+381 60 888 9900',
      city: 'Nis',
      rating: 4.1,
    },
    description:
      'Ford Focus Mk2 1.8, solidan i jeftin za održavanje. Nove kočnice, kaiš zamenjen. Sitan udarac pozadi, prikazano na slikama.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'trip_computer'],
  },
  {
    id: 'skoda-octavia-2-tdi',
    brand: 'Skoda',
    model: 'Octavia',
    generation: 'Mk2',
    year: 2009,
    bodyType: 'Sedan',
    color: 'Candy White',
    mileage: 215000,
    price: 4800,
    city: 'Kraljevo',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/38446754/pexels-photo-38446754.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/38446754/pexels-photo-38446754.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW BKC 1.9 TDI',
      displacement: '1.9L',
      cylinders: 4,
      power: '105 KS (77 kW)',
      torque: '250 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '190 km/h',
      acceleration: '11.0s (0-100)',
    },
    owner: {
      name: 'Radosav J.',
      phone: '+381 64 999 0011',
      city: 'Kraljevo',
      rating: 4.3,
    },
    description:
      'Skoda Octavia Mk2 1.9 TDI, legendarni motor. Praktična, štedljiva, ogroman gepek. DPF uklonjen, nove dizne. Vozilo iz 2009, prvi vlasnik.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'parking_sensors', 'trip_computer'],
  },
  {
    id: 'renault-megane-3',
    brand: 'Renault',
    model: 'Megane',
    generation: 'III',
    year: 2010,
    bodyType: 'Hatchback',
    color: 'Glacier White',
    mileage: 168000,
    price: 3900,
    city: 'Cacak',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/20286882/pexels-photo-20286882.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/20286882/pexels-photo-20286882.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30135418/pexels-photo-30135418.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Renault K9K 1.5 dCi',
      displacement: '1.5L',
      cylinders: 4,
      power: '110 KS (81 kW)',
      torque: '240 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '190 km/h',
      acceleration: '10.8s (0-100)',
    },
    owner: {
      name: 'Biljana M.',
      phone: '+381 65 112 2334',
      city: 'Cacak',
      rating: 4.4,
    },
    description:
      'Renault Megane III 1.5 dCi, veoma štedljiv. Klima, tempomat, navigacija TomTom. Mala ogrebotina na prednjem braniku. Nov kaiš.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'navigation', 'bluetooth', 'trip_computer'],
  },
  {
    id: 'peugeot-308-1.6hdi',
    brand: 'Peugeot',
    model: '308',
    generation: 'T7',
    year: 2009,
    bodyType: 'Hatchback',
    color: 'Nero Black',
    mileage: 182000,
    price: 3600,
    city: 'Zrenjanin',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/16636049/pexels-photo-16636049.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/16636049/pexels-photo-16636049.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/16636019/pexels-photo-16636019.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Peugeot DV6 1.6 HDi',
      displacement: '1.6L',
      cylinders: 4,
      power: '90 KS (66 kW)',
      torque: '205 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '180 km/h',
      acceleration: '12.0s (0-100)',
    },
    owner: {
      name: 'Stevan D.',
      phone: '+381 61 223 3445',
      city: 'Zrenjanin',
      rating: 4.0,
    },
    description:
      'Peugeot 308 1.6 HDi, ekonomičan gradski auto. Poluautomatska klima, panoram. FAP uklonjen. Mala ogrebotina na vozačevim vratima.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'auto_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'panorama', 'fog_lights', 'bluetooth', 'trip_computer'],
  },
  {
    id: 'opel-astra-h',
    brand: 'Opel',
    model: 'Astra',
    generation: 'H',
    year: 2008,
    bodyType: 'Hatchback',
    color: 'Star Silver',
    mileage: 190000,
    price: 2800,
    city: 'Smederevo',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/18833317/pexels-photo-18833317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/18833317/pexels-photo-18833317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/18833314/pexels-photo-18833314.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Opel Z16XER 1.6',
      displacement: '1.6L',
      cylinders: 4,
      power: '116 KS (85 kW)',
      torque: '155 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '190 km/h',
      acceleration: '11.2s (0-100)',
    },
    owner: {
      name: 'Dragan P.',
      phone: '+381 62 334 4556',
      city: 'Smederevo',
      rating: 3.9,
    },
    description:
      'Opel Astra H 1.6, jeftin za trampu. Redovan servis, nove gume napred. Manje tragove upotrebe, ali vozi besprekorno. Idealna prva kola.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'trip_computer'],
  },
  {
    id: 'subaru-impreza-gd',
    brand: 'Subaru',
    model: 'Impreza',
    generation: 'GD',
    year: 2007,
    bodyType: 'Sedan',
    color: 'World Rally Blue',
    mileage: 175000,
    price: 6900,
    city: 'Belgrade',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/19868899/pexels-photo-19868899.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/19868899/pexels-photo-19868899.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/19868901/pexels-photo-19868901.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Subaru EJ253',
      displacement: '2.5L',
      cylinders: 4,
      power: '173 KS (127 kW)',
      torque: '225 Nm',
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'AWD',
      topSpeed: '210 km/h',
      acceleration: '8.5s (0-100)',
    },
    owner: {
      name: 'Aleksa R.',
      phone: '+381 63 445 5667',
      city: 'Belgrade',
      rating: 4.6,
    },
    description:
      'Subaru Impreza 2.5R, AWD i bokser motor. Originalna WR Blue boja, STI pragovi. Redovan servis, glavčine zamenjene. Zvuk izduva je poseban.',
    modifications: ['STI bočni pragovi', 'Sportski izduv'],
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'isofix', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights', 'bluetooth', 'trip_computer'],
  },
  {
    id: 'vw-golf-4-tdi',
    brand: 'Volkswagen',
    model: 'Golf 4',
    generation: 'Mk4',
    year: 2003,
    bodyType: 'Hatchback',
    color: 'Reflex Silver',
    mileage: 240000,
    price: 2200,
    city: 'Leskovac',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/13329676/pexels-photo-13329676.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/13329676/pexels-photo-13329676.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'VW ALH 1.9 TDI',
      displacement: '1.9L',
      cylinders: 4,
      power: '90 KS (66 kW)',
      torque: '210 Nm',
      fuelType: 'Diesel',
      transmission: 'Manual',
      drivetrain: 'FWD',
      topSpeed: '175 km/h',
      acceleration: '12.5s (0-100)',
    },
    owner: {
      name: 'Vladimir S.',
      phone: '+381 60 556 6778',
      city: 'Leskovac',
      rating: 3.8,
    },
    description:
      'Golf 4 1.9 TDI, legendarni ALH motor. Vozi i dan danas. Mala potrošnja, jeftino održavanje. Starost vidi se na laku, ali mehanika čvrsta.',
    equipment: ['abs', 'esp', 'airbags', 'central_lock', 'manual_climate', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'fog_lights'],
  },
  {
    id: 'mercedes-e220-w211',
    brand: 'Mercedes-Benz',
    model: 'E 220 CDI',
    generation: 'W211',
    year: 2006,
    bodyType: 'Caravan',
    color: 'Arctic White',
    mileage: 225000,
    price: 5600,
    city: 'Novi Sad',
    country: 'Serbia',
    image: 'https://images.pexels.com/photos/18837778/pexels-photo-18837778.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    images: [
      'https://images.pexels.com/photos/18837778/pexels-photo-18837778.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/18837782/pexels-photo-18837782.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/18837767/pexels-photo-18837767.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    specs: {
      engine: 'Mercedes OM648',
      displacement: '3.2L',
      cylinders: 6,
      power: '204 KS (150 kW)',
      torque: '500 Nm',
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      topSpeed: '235 km/h',
      acceleration: '7.7s (0-100)',
    },
    owner: {
      name: 'Tomislav B.',
      phone: '+381 61 667 7889',
      city: 'Novi Sad',
      rating: 4.7,
    },
    description:
      'Mercedes E 220 CDI W211 T-Modell, luksuzna karavan. Airmatik vazdušno vešanje, koža, panoram, navigacija. Servisiran, SBC kočnice u redu.',
    equipment: ['abs', 'esp', 'airbags', 'alarm', 'central_lock', 'isofix', 'leather_seats', 'heated_seats', 'auto_climate', 'cruise_control', 'multi_wheel', 'electric_windows', 'alloy_wheels', 'led_xenon', 'panorama', 'fog_lights', 'navigation', 'bluetooth', 'reverse_camera', 'parking_sensors', 'trip_computer'],
  },
];
